obj-y	+=	common/
obj-y	+=	frame_provider/
obj-y	+=	frame_sink/
obj-y	+=	stream_input/
ifdef CONFIG_V4L2_MEM2MEM_DEV
obj-y	+=	amvdec_ports/
endif
obj-y	+=	fake_video_out/
obj-y	+=	framerate_adapter/
obj-y	+=	media_sync/
